# Generated by Django 4.0 on 2021-12-27 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gerenciamento', '0002_auto_20211221_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpraticaesportiva',
            name='postador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
