# Generated by Django 4.0 on 2021-12-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LocalPraticaEsportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('esportes', models.ManyToManyField(
                    related_name='locais_pratica', to='chat.Esporte')),
            ],
        ),
    ]
