# Generated by Django 4.0 on 2021-12-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211221_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpraticaesportiva',
            name='cidade',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localpraticaesportiva',
            name='rua',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
