# Generated by Django 4.0 on 2021-12-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_localpraticaesportiva_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localpraticaesportiva',
            name='esportes',
            field=models.ManyToManyField(related_name='locais_pratica', to='chat.Esporte'),
        ),
    ]
