# Generated by Django 4.0 on 2021-12-23 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerenciamento', '0002_auto_20211221_1855'),
        ('chat', '0005_remove_localpraticaesportiva_esportes_delete_esporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.esporte')),
                ('local_pratica_esportiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.localpraticaesportiva')),
            ],
        ),
    ]
